Name: Price
Description: Price
Properties:
  - Property: price
    Description: price
    Defination:
      commerce: price
    Validation:
      type: number
      min: 0
      max: 999999999999
    Column:
      columnType: numeric
      default: 0
      valueType: number
    UI:
      type: currency
      group: Price

  - Property: cost
    Description: cost
    Defination:
      commerce: price
    Validation:
      type: number
      min: 0
      max: 999999999999
    Column:
      columnType: numeric
      default: 0
      valueType: number
    UI:
      type: currency
      group: Price

Relations:
  - type: ManyToOne
    target: Sku
    name: sku
    eager: true
    onDelete: CASCADE
    nullable: true
    joinColumn: true
    group: Meta
    label: name
    viewColumns:
      - column: name
        as: sku
        valueType: string

      - column: barcode
        as: barcode
        valueType: string

  - type: ManyToOne
    target: Pricelevel
    name: pricelevel
    nullable: true
    group: Meta
    onDelete: CASCADE
    eager: true
    joinColumn: true
    label: name
    viewColumns:
      - column: name
        as: pricelevel
        valueType: string

SearchFields:
  - price
  - cost

Required:
  - price
    - cost
