Name: Message
Description: Message schema
Properties:
  - Property: message
    Description: Message
    Defination:
      lorem: text
    Validation:
      type: string
      minLength: 1
      maxLength: 400

    Column:
      columnType: text
      valueType: string

    UI:
      type: text
SearchFields:
  - message

Required:
  - message

Relations:
  - type: ManyToOne
    target: User
    name: to
    eager: true
    joinColumn: true
    viewColumns:
      - column: username
        as: username
        valueType: string

  - type: ManyToOne
    target: User
    name: from
    eager: true
    joinColumn: true
    viewColumns:
      - column: username
        as: username
        valueType: string
