Name: Pricelevel
Description: Pricelevel schema
Properties:
  - Property: name

    Description: Pricelevel name

    Defination:
      commerce: productDescription

    Validation:
      type: string
      minLength: 3
      maxLength: 20

    UI:
      type: text

    Column:
      columnType: text
      valueType: string

Required:
  - name

Unique:
  - name

SearchFields:
  - id
  - uuid
  - name
