Name: product
Description: Product resource defination
Properties:
  - Property: name
    Description: Product name
    Validation:
      type: string
      minLength: 0
      maxLength: 50
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea
    Defination:
      commerce: productName

  - Property: description
    Description: Product description
    Defination:
      commerce: productDescription
    Validation:
      type: string
      minLength: 3
      maxLength: 500
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea

Relations:
  - ManyToOne:
      target: category
      joinColumn: true
      eager: true
      viewColumns:
        - column: name
          as: category
        - column: id
          as: categoryId

Required:
  - name
  - category
  - department

Unique:
  - name
