Name: Product
Description: Product resource defination
Properties:
  - Property: name
    Description: Product name
    Validation:
      type: string
      minLength: 0
      maxLength: 50
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea
    Defination:
      commerce: productName

  - Property: description
    Description: Product description
    Defination:
      commerce: productDescription
    Validation:
      type: string
      minLength: 3
      maxLength: 500
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea

Relations:
  - type: ManyToOne
    target: Category
    name: category
    eager: true
    joinColumn: true
    viewColumns:
      - column: name
        as: category
        valueType: string
      - column: id
        as: categoryId
        valueType: number

  - type: ManyToOne
    target: Department
    name: department
    eager: true
    joinColumn: true
    viewColumns:
      - column: name
        as: department
        valueType: string

Required:
  - name
  - category
  - department

Unique:
  - name
