Name: Product
Description: Product resource defination
Properties:
  - Property: name
    Validation:
      type: string
      minLength: 3
      maxLength: 50
    Column:
      columnType: text
      valueType: string
    UI:
      type: text
    Defination:
      commerce: productName

  - Property: description
    Description: Product description
    Defination:
      commerce: productDescription
    Validation:
      type: string
      minLength: 0
      maxLength: 500
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea

Relations:
  - type: ManyToOne
    target: Category
    name: category
    eager: true
    joinColumn: true
    nullable: true
    onDelete: SET NULL
    viewColumns:
      - column: name
        as: category
        valueType: string

  - type: ManyToOne
    target: Department
    name: department
    eager: true
    nullable: true
    joinColumn: true
    onDelete: SET NULL
    viewColumns:
      - column: name
        as: department
        valueType: string

Required:
  - name

Unique:
  - name

SearchFields:
  - id
  - uuid
  - name
  - description
  - category
  - department
