Name: Product
Description: Product resource defination
Properties:
  - Property: name
    Validation:
      type: string
      minLength: 3
      maxLength: 50
    Column:
      columnType: text
      valueType: string
    UI:
      type: text
    Defination:
      commerce: productName

  - Property: price
    Validation:
      type: number
      min: 0
      max: 999999999999
    Column:
      columnType: numeric
      valueType: number

    UI:
      type: currency
      group: Price

  - Property: cost
    Validation:
      type: number
      min: 0
      max: 999999999999
    Column:
      columnType: numeric
      valueType: number

    UI:
      type: currency
      group: Price

  - Property: quantity
    Validation:
      type: number
      min: 0
      max: 999999999999
    Column:
      columnType: int
      valueType: number

    UI:
      type: number
      group: Quantity

  - Property: description
    Description: Product description
    Defination:
      commerce: productDescription
    Validation:
      type: string
      minLength: 0
      maxLength: 500
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea

Relations:
  - type: ManyToOne
    group: Meta
    target: Category
    name: category
    eager: true
    joinColumn: true
    nullable: true
    onDelete: SET NULL
    viewColumns:
      - column: name
        as: category
        valueType: string

  - type: ManyToOne
    group: Meta
    target: Department
    name: department
    eager: true
    nullable: true
    joinColumn: true
    onDelete: SET NULL
    viewColumns:
      - column: name
        as: department
        valueType: string

Required:
  - name

Unique:
  - name

SearchFields:
  - id
  - uuid
  - name
  - description
  - category
  - department
