Name: product
Description: Product resource defination
Properties:
  - Property: name
    Validation:
      type: string
      minLength: 0
      maxLength: 50
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea
    Defination:
      commerce: productName

  - Property: description
    Defination:
      commerce: productDescription
    Validation:
      type: string
      minLength: 3
      maxLength: 500
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea

Required:
  - name
  - category
  - department

Unique:
  - name
