Name: Quantity
Description: Quantity
Properties:
  - Property: quantity
    Description: Sku quantity
    Defination:
      random: number
    Validation:
      type: number
      min: -200
      max: 999999999999

    Column:
      columnType: int
      default: 0
      valueType: number

    UI:
      type: number

SearchFields:
  - quantity
  - store
  - sku

Required:
  - quantity
  - sku
  - store

Relations:
  - type: ManyToOne
    target: Sku
    name: sku
    eager: true
    joinColumn: true
    onDelete: CASCADE
    viewColumns:
      - column: name
        as: sku
        valueType: string

      - column: barcode
        as: barcode
        valueType: string

  - type: ManyToOne
    target: Store
    name: store
    eager: true
    joinColumn: true
    onDelete: SET NULL
    viewColumns:
      - column: name
        as: store
        valueType: string
