openapi: '3.0.2'
info:
  title: Sample Component
  version: 1.0.0

paths:
  '/api/sample':
    get:
      operationId: getSamples
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateSampleDto'
      security:
        - inventory_auth:
            - login
        - permission:
            - read:sample
components:
  schemas:
    CreateSampleDto:
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 10
          uniqueItems: true

        description:
          type: string
          minLength: 3
          maxLength: 400

        category:
          type: object
          properties:
            id:
              type: number
          $ref: '#/components/schemas/CreateSampleDto'

      required:
        - name
        - description
