Name: Sku
Description: Stock tracking unit
Properties:
  - Property: name
    Description: SKU name
    Validation:
      type: string
      minLength: 0
      maxLength: 30
    Column:
      columnType: text
      valueType: string
    UI:
      type: text
    Defination:
      random: alpha

  - Property: barcode
    Description: SKU Barcode
    Validation:
      type: string
      minLength: 10
      maxLength: 13
    Column:
      columnType: text
      valueType: string
    UI:
      type: text
    Defination:
      random: alphaNumeric

  - Property: description
    Description: Sku description
    Defination:
      commerce: productDescription
    Validation:
      type: string
      minLength: 0
      maxLength: 500
    Column:
      columnType: text
      valueType: string
    UI:
      type: textarea

Relations:
  - type: ManyToOne
    target: Product
    name: product
    eager: true
    joinColumn: true
    onDelete: CASCADE
    viewColumns:
      - column: name
        as: product
        valueType: string

Required:
  - name
  - barcode
  - product

Unique:
  - name
  - barcode

SearchFields:
  - id
  - uuid
  - name
  - barcode
  - description
  - product
