Name: User
Description: User resource metadata
Properties:
  - Property: username
    Description: Username
    Defination:
      internet: userName
    Validation:
      type: specific
      email: true
    UI:
      type: email
      group: Username
    Column:
      columnType: text
      valueType: string

  - Property: code
    Description: Code
    Defination:
      lorem: text
    Validation:
      type: string
      minLength: 1
      maxLength: 100
    UI:
      type: text
      group: Code
    Column:
      columnType: text
      valueType: string

  - Property: password
    Description: User password
    Defination:
      internet: password
    Validation:
      type: specific
      password: true
    Column:
      columnType: text
      valueType: string
      hash: true
    UI:
      type: password
      group: Password

Relations:
  - type: ManyToMany
    target: Permission
    name: permission
    eager: true
    joinTable: true
    nullable: true
    group: Permissions
    onDelete: CASCADE
    label: description

Required:
  - username
  - password
SearchFields:
  - username

Unique:
  - username
