name: transaction
mainProperty: complete
properties:
  - name: complete
    type: enum
    inputElement: select
    enum:
      - complete
      - canceled

  - name: orders
    type: one-to-many
    inputElement: search-item
    from: order
    mainProperty: user
