export * from './lib/card-view-resource';
export * from './lib/create-resource';
export * from './lib/data-services';
export * from './lib/delete-resource';
export * from './lib/material.module';
export * from './lib/resource-layout';
export * from './lib/statistic-view-resource';
export * from './lib/table-view-resource';
export * from './lib/update-resource';
